temp: utils: Action.java build fix
 * frameworks/base/core/java/com/android/internal/util/gzosp/Action.java:258: error: method dismissKeyguard in interface IWindowManager cannot be applied to given types;
            WindowManagerGlobal.getWindowManagerService().dismissKeyguard();
                                                       ^
  required: IKeyguardDismissCallback
  found: no arguments
  reason: actual and formal argument lists differ in length

  * need to fix that when time permits, or someone should

Change-Id: I8202050b81b3c0fdd3e42718d50fefaf69d6a3a3